steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/red-carver-396207/quickstart-docker-repo/quickstart-imageiii', '.' ]
images:
- 'us-west2-docker.pkg.dev/red-carver-396207/quickstart-docker-repo/quickstart-imageiii'